# Generated by Django 2.1.1 on 2018-09-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='日期')),
                ('nickname', models.CharField(max_length=10)),
                ('total_score', models.FloatField(default=0)),
                ('read_score', models.FloatField(default=0)),
                ('interact_score', models.FloatField(default=0)),
                ('social_score', models.FloatField(default=0)),
                ('close_score', models.FloatField(default=0)),
                ('repost_num', models.IntegerField(default=0)),
                ('comment_num', models.IntegerField(default=0)),
                ('story_num', models.IntegerField(default=0)),
                ('interact_num', models.IntegerField(default=0)),
                ('search_num', models.IntegerField(default=0)),
                ('mention_num', models.IntegerField(default=0)),
                ('social_num', models.IntegerField(default=0)),
                ('blog_num', models.IntegerField(default=0)),
                ('read_num', models.IntegerField(default=0)),
                ('flower_people_num', models.IntegerField(default=0)),
                ('flower_count_num', models.IntegerField(default=0)),
                ('close_num', models.IntegerField(default=0)),
            ],
        ),
    ]
